### ISSUE TITLE
Mejoras en tareas

### ISSUE THREAD

**Issue by davcamalv** [angel96/scrume-back#10]
Esta issue esta dedicada a aquellas peticiones de front relacionadas con tareas, asi como la resolucion de fallos y el desarrollo de test faltantes.

**Comment by aleks-rodriguez** [comment]
Realizada mejora en el JSON que devuelve el método de buscar una tarea a petición de Front.

**Comment by aleks-rodriguez** [comment]
Realizada petición de front de un método que devuelva las task, proyecto y workspace, si lo hubiera, de un usuario.
