### ISSUE TITLE
Revisión casos de uso de David

### ISSUE THREAD

**Issue by davcamalv** [angel96/scrume-back#20]
Revisión de los casos de uso de equipo, sprint, user, estimaciones y sus respectivos tests.

**Comment by aleks-rodriguez** [comment]
Lo que he encontrado:

- [ ] En Team, hay veces que al no estar autentificado, da un error de casting, "class java.lang.String cannot be cast to class spring.Model.UserAccount. Aún con eso, debería bloquearlo el contexto de seguridad de Spring.
- [ ] En Team, findByNick no tiene validaciones sobre si el team y/o los usuarios existen. Si team o users llegan a null, salta NullPointerException, no está controlado
