### ISSUE TITLE
CU10 - Gestión de pagos

### ISSUE THREAD

**Issue by davcamalv** [angel96/scrume-back#8]
- [x] RI - Un registro de pagos debe tener el usuario, la box y la fecha de realización del pago.

- [x] RF - Al efectuarse el pago del paquete, este debe guardarse en el registro correspondiente.
(7 PH)

**Comment by angel96** [comment]
# Consideraciones

1. La box deberia de estar asignada al pago, no al usuario. Cambio en el modelo actual.

2. ¿No deberiamos dar la opción de añadir nuevos paquetes de pagos por parte de los administradores de la plataforma?
